### ISSUE TITLE
Panic: Cannot open prevstates/account

### ISSUE THREAD

**Issue by faddat** [lino-network/testnets#2]
When attempting to join the latest test network, I get:

panic: failed to open open /home/pi/.lino/prevstates/account: no such file or directory

Do I need to import the previous state for this to work correctly?  

Thanks

PS I'll try doing that and report back...

**Comment by faddat** [comment]
When I import the previous state, it works.  

Sadly, my Raspberry Pi also croaks and runs out of RAM.  Got any idea what RAM usage is like for linod?

**Comment by xiaoxiaff** [comment]
@faddat since we need to import all previous blockchain data it would require at least 16GB memory.
